### ISSUE TITLE
UTF8 error ?

### ISSUE THREAD

**Issue by golgoth777** [Sylvain-Bugat/RundeckMonitor#9]
Hello,

I use RundeckMonitor since a few monthes and appreciates this great tool.

Am facing an issue, after relocating my rundeck server, the RundeckMonitor couldn't start on my laptop :

2015-08-15 10:29:38,403 [main] ERROR c.g.s.rundeckmonitor.RundeckMonitor:main(53
7) - Rundeck Monitor startup error: org.rundeck.api.RundeckApiException: Failed
to read Rundeck response
        at org.rundeck.api.parser.ParserHelper.loadDocument(ParserHelper.java:47
)
        at org.rundeck.api.ApiCall$ParserHandler.handle(ApiCall.java:488)
        at org.rundeck.api.ApiCall.execute(ApiCall.java:418)
        at org.rundeck.api.ApiCall.get(ApiCall.java:173)
        at org.rundeck.api.RundeckClient.getExecutions(RundeckClient.java:1600)
        at com.github.sbugat.rundeckmonitor.RundeckMonitor.updateRundeckHistory(
RundeckMonitor.java:331)
        at com.github.sbugat.rundeckmonitor.RundeckMonitor.<init>(RundeckMonitor
.java:106)
        at com.github.sbugat.rundeckmonitor.RundeckMonitor.main(RundeckMonitor.j
ava:524)
Caused by: org.dom4j.DocumentException: Invalid byte 2 of 3-byte UTF-8 sequence.
 Nested exception: Invalid byte 2 of 3-byte UTF-8 sequence.
        at org.dom4j.io.SAXReader.read(SAXReader.java:484)
        at org.dom4j.io.SAXReader.read(SAXReader.java:343)
        at org.rundeck.api.parser.ParserHelper.loadDocument(ParserHelper.java:45
)
        ... 7 common frames omitted

2015-08-15 10:31:10,227 [main] ERROR c.g.s.r.tools.SystemTools:exit(57) - RunDec
k Monitor exit with code 1

Is it the fact that my rundeck install uses UTF-8 instead of ASCII that produces this result ?
Has someone already faced this ?

Thx

**Comment by Sylvain-Bugat** [comment]
Hello,

it's a bug in the [https://github.com/rundeck/rundeck-api-java-client](rundeck-api-java-client), some non-ascii/UTF-8 character like é, è, à, etc. seems to cannot be decoded in the SAXReader used by the java Rundeck client.
Do you use any non-ascii character in your job definitions? How do your Rundeck installation uses UTF-8 instead of ASCII?

Rundeck Monitor get the 10 latest failed job by default and one or more of these execution contains some non-ascii characters.
The current workaround is to edit all jobs and replace non-ascii character by ascii one (you can export jobs to do a mass replace or to see with come grep command where are non-ascii characters) AND generate new 10 latest failed executions with a test command like `unknowncmd`.

**Comment by golgoth777** [comment]
Merci pour le contournement.

**Comment by srininad** [comment]
Hello, I downloaded rundeck monitor and was trying to use it on rundeck 2.8 version on rhel7. I am getting following error.
[main] ERROR c.g.s.r.tools.SystemTools:exit(57) - RunDeck Monitor exit with code 2

and the export display throws

![image](https://cloud.githubusercontent.com/assets/21369510/18142264/62b9277e-6f82-11e6-9e95-0c14d3180bc9.png)

Could you please help

Thanks,
Srini

**Comment by Sylvain-Bugat** [comment]
Hello,
Please open a new issue with some response to theses questions.
Which desktop or window manager do you use on rhel 7.1? Does it have a system tray area?
